export const branches = {
  MEVARAM: "MEVARAM",
  TRIVANDRUM: "TRIVANDRUM",
  ATTINGAL: "ATTINGAL",
  KOLLAM: "KOLLAM",
  KOTTARAKKARA: "KOTTARAKKARA",
  PATHANAMTHITTA: "PATHANAMTHITTA",
  KARUNAGAPPALLY: "KARUNAGAPPALLY",
};

export const courses = {
  IELTS_1_MONTH: "IELTS 1 MONTH",
  IELTS_2_MONTH: "IELTS 2 MONTH",
  IELTS_3_MONTH: "IELTS 3 MONTH",
  OET_1_MONTH: "OET 1 MONTH",
  OET_2_MONTH: "OET 2 MONTH",
  OET_3_MONTH: "OET 3 MONTH",
};

export const departments = {
  IELTS: "IELTS",
  OET: "OET",
};
